---

- name: Setup AWS EC2 instances
  include_tasks: manage.yml
  when: instance_group != 'all'
  vars:
    instance_values: "{{ host_items.value }}"
    instance_exp: "{{ host_items.key }}"
    instance_group: "{{ host_group_name }}{{ separator }}{{ instance_exp }}"
    ec2config: "{{ host_group_vars \
                  | combine( exp_base ) \
                  | combine({ \
                      'instance_tag': prj_id + '_' + instance_group,
                    }) \
               }}"
  loop: "{{ host_exp_values | dict2items }}"
  loop_control:
    loop_var:
      host_items
