---

- assert:
    that:
    - do_create_vpc is defined

- debug:
    msg: "-> creating VPC..."
  tags: [print_action]
  when: do_create_vpc

- name: Create VPC in AWS
  include_role:
    name: experiment-aws-vpc-create
  when: do_create_vpc

- debug:
    msg: "-> deleting VPC.."
  tags: [print_action]
  when: not do_create_vpc

- name: Delete VPC in AWS
  include_role:
    name: experiment-aws-vpc-clear
  when: not do_create_vpc
