---

- assert:
    that:
      - exp_job_ids_completing is defined
      - exp_name is defined


- name: Remove finished job with downloaded results from queue
  tsp:
    remove_task_labels: "{{ exp_job_ids_completing | map('to_json') | map('string') }}"
  delegate_to: "{{ host }}"
  loop: "{{ groups[exp_name] }}"
  loop_control:
    loop_var: host