---

##########################################################################
#   Load Experiment State and Setup AWS                                  #
##########################################################################
- name: Load Experiment State and Setup AWS
  hosts: localhost

  tasks:
  - name: Load an Experiment Run (init a new run if it does not exist yet)
    include_role:
      name: experiment-state
    vars:
      expstate: load
  
  - name: Schedule the experiments (job ids are 0 to number of experiments-1)
    set_fact:
      exp_job_ids: "{{range(0, exp_runs_ext | length, 1) | product(range(0, n_repetitions, 1)) | map('join', '_') | list }}"
    when: id == 'new' # only schedule if it is a new experiment

  - name: Set all jobs to unfinished and pending
    set_fact:
      exp_job_ids_unfinished: "{{ exp_job_ids }}" 
      exp_job_ids_pending: "{{ exp_job_ids }}" 
    when: id == 'new' # only schedule if it is a new experiment


  - name: Save the updated state of the experiment (save job ids)
    include_role:
      name: experiment-state
    vars:
      expstate: save
    when: id == 'new' # only persist the state if it is a new experiment

  - debug:
      msg: "Running Experiment: {{ exp_name }} (id={{ exp_id }})   #runs={{ exp_runs_ext | length }} #reps={{ n_repetitions }}  => #jobs={{ exp_job_ids | length }}"
    tags: [print_action]

  - debug:
      msg: "Setup AWS..."
    tags: [print_action]
    when: id == 'new'

  - name: Setup AWS including VPC and the required EC2 instances
    include_role:
      name: experiment-aws
    vars:
      server_ec2_instances_num: "{{ exp_server.ec2_instances_num }}"
      server_ec2_instances_max_num: "{{ exp_server.ec2_instances_max_num }}"
      client_ec2_instances_num: "{{ exp_client.ec2_instances_num }}"
      client_ec2_instances_max_num: "{{ exp_client.ec2_instances_num }}"
    when: id == 'new' # only change AWS if it is a new experiment

  - debug:
      var: groups

  - debug:
      msg: "Setup Host Machines..."
    tags: [print_action]

##########################################################################
#   Setup Machines (Common, Clients Only, Servers Only)                  #
##########################################################################



- name: Setup machines with common setup
  hosts: "{{ hostvars['localhost'].exp_client.host_group }}:{{ hostvars['localhost'].exp_server.host_group }}"
  tasks:
  - debug:
      var: groups
  - name: 
    include_role:
      name: setup-common
    when: id == 'new' # only setup if it is a new experiment

- name: Setup "server" machines with server-specific setup
  hosts: "{{ hostvars['localhost'].exp_server.host_group }}"
  tasks:
  - debug:
      var: groups
  - name: 
    include_role:
      name: setup-server
    when: id == 'new' # only setup if it is a new experiment

- name: Setup "client" machines with client-specific setup
  hosts: "{{ hostvars['localhost'].exp_client.host_group }}"
  tasks:
  - debug:
      var: groups
  - name: 
    include_role:
      name: setup-client
    when: id == 'new' # only setup if it is a new experiment


##########################################################################
#   Run Experiment Jobs                                                  #
##########################################################################

- name: Run and monitor experiment jobs
  # variables 'exp_n_tries' and 'exp_check_wait_time' control how long this runs
  hosts: localhost
  tasks:
  - debug:
      msg: "Running Experiment Jobs..."
    tags: [print_action]

  - name: Try to sequentially run an experiment and wait until it's finished
    include_role:
      name: experiment-job
    when: exp_job_ids_unfinished | length > 0  # there are some unfinished jobs left
    loop: "{{ range(0, exp_n_tries, 1)|list }}"

  
##########################################################################
#   Cleanup AWS (terminate instances, remove vpc)                        #
##########################################################################

- name: Cleanup and Utility
  hosts: localhost
  tasks:

  - debug:
      msg: "Cleanup AWS..."
    tags: [print_action]
    when: awsclean | default(true) | bool  and exp_job_ids_unfinished | length == 0

  - name: Cleanup AWS
    include_role:
      name: experiment-aws
    vars:
      server_ec2_instances_num: 0
      server_ec2_instances_max_num: 0
      client_ec2_instances_num: 0
      client_ec2_instances_max_num: 0
    when: awsclean | default(true) | bool  and exp_job_ids_unfinished | length == 0

  - name: Output the run id of this experiment for convenience
    debug:
      var: exp_id
    when: id == 'new'

  - debug:
      msg: "Finished Experiment: {{ exp_name }} (id={{ exp_id }})   #runs={{ exp_runs_ext | length }} #reps={{ n_repetitions }}  => #jobs={{ exp_job_ids | length }}"
    tags: [print_action]
    when: exp_job_ids_unfinished | length == 0