---

- assert:
    that:
    - ec2config is defined

- name: Launching ansible controller EC2 instance
  ec2:
    instance_type: '{{ ec2config.instance_type }}'
    key_name: '{{ ec2config.key_name }}'
    image: '{{ ec2config.ec2_image }}'
    region: '{{ ec2config.aws_region }}'
    group: '{{ ec2config.sg_name }}'
    wait: yes
    assign_public_ip: yes
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        snapshot: '{{ ec2config.ec2_volume_snapshot }}'
        volume_size: '{{ ec2config.ec2_volume_size }}'
        delete_on_termination: True
    instance_tags:
      Name: ansible_controller
  register: ec2_launch

- name: Refresh dynamic ec2 inventory
  meta: refresh_inventory

- name: Wait for SSH to come up
  delegate_to: "{{ public_dns_name }}"
  wait_for_connection:
    connect_timeout: 3
    timeout: 320
  loop: "{{ ec2_launch.instances
              | map(attribute='public_dns_name')
              | list }}"
  loop_control:
    loop_var: public_dns_name
