
- name: Create folder for SEAL
  ansible.builtin.file:
    path: "{{ SEAL_INSTALL_PATH }}"
    state: directory

- name: "Clone SEAL version {{ SEAL_VERSION }}"
  ansible.builtin.git:
    repo: https://github.com/microsoft/SEAL.git
    dest: "{{ SEAL_INSTALL_PATH }}"
    version: "{{ SEAL_VERSION }}"

- name: Build SEAL
  block:
    - ansible.builtin.command:
        cmd: cmake -DSEAL_THROW_ON_TRANSPARENT_CIPHERTEXT=OFF -S . -B build
        chdir: "{{ SEAL_INSTALL_PATH }}/SEAL"

    - ansible.builtin.command:
        cmd: cmake --build build
        chdir: "{{ SEAL_INSTALL_PATH }}/SEAL"

- name: Install SEAL
  ansible.builtin.command:
    cmd: cmake --install build
    chdir: "{{ SEAL_INSTALL_PATH }}/SEAL"
  become: yes
  become_method: sudo
