---
plugin: aws_ec2
regions:
  - eu-central-1
filters:
  instance-state-name: ["running"]

# keyed_groups may be used to create custom groups
strict: False
keyed_groups:
# Add hosts to tag_name_value groups for each Name/Value tag pair
  - prefix: tag
    key: tags
