---

# This role is always executed an ensures that the task spooler is installed and the code repository is downloaded.

- debug:
    msg: "-> setup suite"
  tags: [print_action]

- name: Update repositories cache and install required packages
  become: True
  apt:
    pkg:
    - task-spooler
    update_cache: yes


# Use ssh-agent to get code from Git Remote Repository:
#
# 1. Configure ~/.ssh/config:  (add to file and replace the key for example with aws_ppl.pem)
#    ```
#    Host ec2*
#    IdentifyFile ~/.ssh/{{ exp_base.key_name }}
#    ForwardAgent yes
#    ```
#
# 2. Add the GitHub private key to ssh-agent:
#
#   ssh-aadd ~/.ssh/private_key_rsa
#
# 3. (On a MAC, need add to keychain)
- name: Update Code from Git remote repository
  git:
    repo: "{{ git_remote_repository }}"
    dest: "{{ remote.dir }}/code"
    accept_hostkey: yes
    force: yes

  # TODO [nku] transform such that we can clone a list of repositories