---

# This role terminates all ec2 instances of the project or suite.
# (there is a sanity check (delay) that allows the user to abort)

# Parameters:
# filter_by_suite: (default: False) if True -> expects that `suite` is defined and then we only delete instances with this suite tag
# instance_ids_in_use: (default: []) list of instance ids to exclude (i.e., not to delete)

- assert:
    that:
    - inventory_hostname == 'localhost'

- set_fact:
    my_ec2_filter:
      "tag:prj_id": "{{ prj_id }}"
  when: not (filter_by_suite | default(False))

- set_fact:
    my_ec2_filter:
      "tag:prj_id": "{{ prj_id }}"
      "tag:suite": "{{ suite }}"
  when: filter_by_suite | default(False)

- community.aws.ec2_instance_info:
      region: "{{ exp_base.aws_region }}"
      filters: "{{ my_ec2_filter }}"
  register: ec2_instance_info

- name: Extract instance ids of ec2 instances to remove
  set_fact:
    ec2_instance_ids: "{{ ec2_instance_info | json_query(query) | difference(instance_ids_in_use | default([]) | list ) | list }}"
  vars:
    query: instances[?state.name !='terminated'].instance_id

- pause:
    seconds: 10
    prompt: |
      "Removing instances with the following ids:
       {{ ec2_instance_ids }}

       If the above instance IDs are wrong, abort now! (CTRL+C followed by 'A')"
  when: (ec2_instance_ids | length) > 0
  tags: [print_action]


- name: Cleanup AWS
  community.aws.ec2_instance:
    region: "{{ exp_base.aws_region }}"
    instance_ids: "{{ ec2_instance_ids }}"
    state: absent
  when: (ec2_instance_ids | length) > 0
