
- name: Create EC2 Instances (only assign subset of tags yet)
  community.aws.ec2_instance:
    instance_type: '{{ ec2config.instance_type }}'
    key_name: '{{ ec2config.key_name }}'
    image_id: '{{ ec2config.ec2_image_id }}'
    region: '{{ ec2config.aws_region }}'
    security_group: '{{ ec2config.sg_name }}'
    vpc_subnet_id: '{{ ec2config.vpc_subnet_id }}'
    wait: yes
    network:
      assign_public_ip: yes
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: gp2
          snapshot_id: '{{ ec2config.ec2_volume_snapshot }}'
          volume_size: '{{ ec2config.ec2_volume_size }}'
          delete_on_termination: True
    tags:
      prj_id: "{{ prj_id }}"
      suite: "{{ suite }}"
      host_type: "{{ host_type }}"

  # This is a workaround for the missing "exact_count" feature that used to be
  # in the deprecated community.aws.ec2
  # - https://github.com/ansible/ansible/issues/49944
  loop: "{{ range(0, n_sum | int) | list }}"
  loop_control:
    loop_var: instance_cnt
