---
# NOTE: At the moment `bsub` (LSF) is not used for scheduling tasks
#       but we leave the scheduler if we want to add a cloud later that uses LSF

- assert:
    that:
      - exp_jobs_to_enqueue is defined
      - exp_name is defined


- name: schedule the job on leonhard using bsub
  vars:
    experiment_name: "{{ job.job_info | safe_job_info_string }}"
    output_file: "{{ job.exp_working_dir }}/results/stdout.log"
    error_file: "{{ job.exp_working_dir }}/results/stderr.log"
  register: bsub_output
  shell: |
    source /etc/profile
    source ~/.bash_profile
    . /cluster/apps/local/env2lmod.sh
    module load {{ euler_base_env }} {{ euler_env }}
    bsub -W {{ euler_job_minutes }} -n {{ euler_cpu_cores }} -J {{ experiment_name }} -oo {{ output_file }} -eo {{ error_file }} -R "rusage[mem={{ euler_cpu_mem_per_core_mb }},ngpus_excl_p={{ euler_gpu_number }}]" -R "select[{{ 'gpu_model0==' + euler_gpu_model if euler_gpu_model is not none else 'gpu_mtotal0>=' + euler_gpu_min_mem_per_gpu_mb | string }}]" "{{ job.exp_run_cmd }}"
  args:
    chdir: "{{ job.exp_working_dir }}"
    executable: /bin/bash
  delegate_to: "{{ job.host_info.ansible_host_id }}"
  loop: "{{ exp_jobs_to_enqueue }}"
  loop_control:
    loop_var: job
