---

- assert:
    that:
      - exp_jobs_to_enqueue is defined
      - exp_name is defined

- name: Clear task spooler queue on each host (+ stop all running jobs)
  tsp:
    clear_tasks: True
  delegate_to: "{{ host }}"
  loop: "{{ groups[exp_name] }}"
  loop_control:
    loop_var: host

- name: Enqueue all jobs on the task spooler
  tsp:
    cmd: "{{ job.exp_run_cmd }}"
    cmd_label: "{{ job.job_info | to_json | string }}"
    cmd_working_dir: "{{ job.exp_working_dir }}"
    cmd_stdout_file: results/stdout.log # relative path compared to working dir
    cmd_stderr_file: results/stderr.log
  delegate_to: "{{ job.host_info.ansible_host_id }}"
  loop: "{{ exp_jobs_to_enqueue }}"
  loop_control:
    loop_var: job