---


# This role deletes the docker network of the suite.

# NOTE: since we don't have a network per suite and instead have one per project it could be problematic to delete it here.
# (it will just fail because there are other instances attached, so not a big deal)

- debug:
    msg: "-> deleting Docker Network.."
  tags: [print_action]

- name: Delete Docker Network
  community.docker.docker_network:
    name: "{{ exp_base.vpc_name }}"
    state: absent
    force: true
