
- name: "Clone the AWS Ansible Experiment Suite from {{ ansible_exp_suite_git_repo }}"
  git:
    repo: "{{ ansible_exp_suite_git_repo }}"
    dest: "{{ ansible_controller_aes_dir }}"
    key_file: "{{ ansible_controller_ssh_key_path }}"

- name: Set permissions on cloned repo
  file:
    path: "{{ ansible_controller_aes_dir }}"
    owner: "{{ ansible_controller_user }}"
    group: "{{ ansible_controller_group }}"
    mode: '0750'
    recurse: yes
