
- name: Set variables for the CLI installation
  set_fact:
    ansible_controller_awscli_dir: "{{ ansible_controller_home }}/awscli"
    awscli_url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    awscli_zip_dest: "{{ ansible_controller_awscli_dir }}/awscli-exe-linux-x86_64.zip"
    awscli_pub_key_path: "{{ ansible_controller_awscli_dir }}/aws_cli_team_gpg_key.pub"

- block:
  - name: Create a folder for the AWS CLI installer
    ansible.builtin.file:
      path: "{{ ansible_controller_awscli_dir }}"
      state: directory
      owner: "{{ ansible_controller_user }}"
      group: "{{ ansible_controller_group }}"
      mode: '0750'

  - name: Copy AWS CLI Team GPG public key to VM
    ansible.builtin.copy:
      src: resources/awscli/aws_cli_team_gpg_key.pub
      dest: "{{ awscli_pub_key_path }}"
      owner: "{{ ansible_controller_user }}"
      group: "{{ ansible_controller_group }}"
      mode: '0440'

  - name: Import AWS CLI Team GPG public key in GPG
    ansible.builtin.command: "gpg --import {{ awscli_pub_key_path }}"

  - name: Download AWS CLI ZIP-file
    ansible.builtin.get_url:
      url: "{{ awscli_url }}"
      dest: "{{ awscli_zip_dest }}"
      owner: "{{ ansible_controller_user }}"
      group: "{{ ansible_controller_group }}"
      mode: '0440'
    register: get_url

  - name: Download signature for AWS CLI ZIP-file
    ansible.builtin.get_url:
      url: "{{ awscli_url }}.sig"
      dest: "{{ awscli_zip_dest }}.sig"
      owner: "{{ ansible_controller_user }}"
      group: "{{ ansible_controller_group }}"
      mode: '0440'

  - name: Verify signature for AWS CLI ZIP-file
    ansible.builtin.command:
      cmd: "gpg --verify {{ awscli_zip_dest }}.sig {{ awscli_zip_dest }}"
    register: gpg_cmd

  - name: Abort playbook for failed verification
    ansible.builtin.fail:
      msg: |
        Failed to verify signature for AWS CLI ZIP-file! Check the official verification
        guide [1] to understand why the verification failed.

        [1] https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#v2-install-linux-validate
    when: gpg_cmd.rc != 0

  - name: Unzip AWS CLI tools
    ansible.builtin.unarchive:
      src: "{{ awscli_zip_dest }}"
      dest: "{{ ansible_controller_awscli_dir }}"
      owner: "{{ ansible_controller_user }}"
      group: "{{ ansible_controller_group }}"
      remote_src: yes

  - name: Check if AWS CLI is already installed
    ansible.builtin.command: which aws
    register: which_cmd

  - name: Install AWS CLI (if it is not yet installed)
    ansible.builtin.command:
      cmd: ./aws/install
      chdir: "{{ ansible_controller_awscli_dir }}"
    when: which_cmd.rc != 0

  - name: Update AWS CLI (if awscli is already installed)
    ansible.builtin.command:
      cmd: ./aws/install --update
      chdir: "{{ ansible_controller_awscli_dir }}"
    when: which_cmd.rc == 0

  - name: Verify installation
    block:
      - ansible.builtin.command: "sudo -u '{{ ansible_controller_user }}' aws --version"
        register: awscli_cmd

      - ansible.builtin.debug:
          msg: "Installed AWS CLI version {{ awscli_cmd.stdout }}"
        tags: [print_action]
        when: awscli_cmd.rc == 0

      - ansible.builtin.fail:
          msg: AWS CLI installation failed!
        when: awscli_cmd.rc != 0

  become: yes
  become_method: sudo
