
- name: Set variables for the CLI installation
  set_fact:
    ansible_controller_awscli_dir: {{ ansible_controller_home }}/awscli
    awscli_url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    awscli_zip_dest: "{{ ansible_controller_awscli_dir }}/awscli-exe-linux-x86_64.zip"
    awscli_pub_key_path: "{{ ansible_controller_awscli_dir }}/aws_cli_team_gpg_key.pub"

- block:
    - name: Create a folder for the AWS CLI installer
      file:
        path: "{{ ansible_controller_awscli_dir }}"
        state: directory
        mode: '0750'

    - name: Copy AWS CLI Team GPG public key to VM
      copy:
        src: resources/awscli/aws_cli_team_gpg_key.pub
        dest: "{{ awscli_pub_key_path }}"
        mode: '0440'

    - name: Import AWS CLI Team GPG public key in GPG
      command:
        cmd: "gpg --import {{ awscli_pub_key_path }}"

    - name: Download AWS CLI ZIP-file
      get_url:
        url: "{{ awscli_url }}"
        dest: "{{ awscli_zip_dest }}"
        mode: '0440'
      register: get_url

    - name: Download signature for AWS CLI ZIP-file
      get_url:
        url: "{{ awscli_url }}.sig"
        dest: "{{ awscli_zip_dest }}.sig"
        mode: '0440'

    - name: Verify signature for AWS CLI ZIP-file
      command:
        cmd: "gpg --verify {{ awscli_zip_dest }}.sig {{ awscli_zip_dest }}"
      register: gpg_cmd

    - name: Abort playbook for failed verification
      fail:
        msg: |
          Failed to verify signature for AWS CLI ZIP-file! Check the official verification
          guide [1] to understand why the verification failed.

          [1] https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#v2-install-linux-validate
      when: gpg_cmd.rc != 0

    - name: Unzip AWS CLI tools
      unarchive:
        src: "{{ awscli_zip_dest }}"
        dest: "{{ ansible_controller_awscli_dir }}"
        remote_src: yes

    - name: Install AWS CLI tools
      command:
        cmd: ./aws/install
        chdir: "{{ ansible_controller_awscli_dir }}"

    - name: Verify installation
      block:
        - command:
          cmd: awscli --version
        register: awscli_cmd

        - debug:
            msg: "Installed AWS CLI version {{ awscli_cmd.stdout }}"
          tags: [print_action]
          when: awscli_cmd.rc == 0

        - fail:
            msg: AWS CLI installation failed!
          when: awscli_cmd.rc != 0

  become: yes
  become_user: "{{ ansible_controller_user }}"
