
- name: Install ansible
  ansible.builtin.pip:
    name: ansible
    executable: pip3
  become: yes
  become_method: sudo

- name: Install the required Ansible collections
  ansible.builtin.command:
    cmd: pipenv run ansible-galaxy install -r requirements-collections.yml
    chdir: "{{ ansible_controller_does_dir }}"
