
- name: Set shared SSH variables
  set_facts:
    ssh_key_dir: "{{ ansible_controller_ssh_key_dir }}"
    ssh_key_owner: "{{ ansible_controller_user }}"
    ssh_key_group: "{{ ansible_controller_group }}"
    ssh_key_type: "{{ ansible_controller_ssh_key_type }}"
    ssh_key_size: "{{ ansible_controller_ssh_key_size }}"

- name: Generate SSH key for Git
  include_role:
    name: setup_ssh.yml
    vars:
      ssh_key_path: "{{ ansible_controller_git_ssh_key_path }}"
  when: ansible_exp_suite_private_repo

- name: Generate SSH key for AWS
  include_role:
    name: setup_ssh.yml
    vars:
      ssh_key_path: "{{ ansible_controller_aws_ssh_key_path }}"

- name: Add entry for EC2 hosts to ~/.ssh/config
  blockinfile:
    path: "{{ ansible_controller_ssh_key_dir }}/config"
    block: |
      Host ec2*
      IdentityFile {{ ansible_controller_aws_ssh_key_path }}
      User ubuntu
      ForwardAgent yes
    create: yes
    state: present

  become: yes
  become_user: "{{ ssh_key_owner }}"
