---

instance_type: {{ cookiecutter.host_ec2_instance_type  }}
ec2_volume_size: {{ cookiecutter.host_ec2_volume_size  }}

ec2_image_id:  {{ cookiecutter.host_ec2_ami }}
ec2_volume_snapshot: {{ cookiecutter.host_ec2_volume_snapshot }}
