---


# TODO [nku] could integrate the ip address / username as cookiecutter params

# TODO [nku] think about whether the ansible_user should be set here or as environment variable

all:
  children:
    {{ cookiecutter.host_name }}: # corresponds to an entry under `host_types` in suite designs (and to doe-suite-config/group_vars/<HOST-TYPE-1>` folder)
      hosts:      # multiple instances of the same host_type (see parameter `n` in suite designs)
        {{ cookiecutter.host_name }}_01:
          ansible_host: <IP ADDRESS or DNS> # (connect to this host via ssh)
          ansible_user: <USERNAME> #(login ssh username)
#        <HOST-ID-2>:
#          ansible_host: <IP ADDRESS or DNS>
#          ansible_user: <USERNAME>
#
#    <HOST-TYPE-2>: # another host type
#      hosts:
#         <HOST-ID-3>:
#          ansible_host: <IP ADDRESS or DNS>
#          ansible_user: <USERNAME>