---

- assert:
    that:
    - host_group_name is defined
    - host_values is defined
    - host_values.n is defined
    - host_values.n_max is defined
    - (host_values.n_max | int) >= (host_values.n | int)

- name: "Manually load variables for host in group '{{ host_group_name }}'"
  include_vars:
    file: "group_vars/{{ host_group_name }}/main.yml"
    name: host_group_vars

- debug:
    msg: "-> creating EC2 instance for group '{{ host_group_name }}'..."
  tags: [print_action]
  when: (host_values.n_max | int) > 0

- debug:
    msg: "-> terminating EC2 instances for group '{{ host_group_name }}'..."
  tags: [print_action]
  when: (host_values.n_max | int) == 0

- name: Create EC2 Instances
  include_role:
    name: experiment-aws-ec2
  vars:
    ec2config: "{{ host_group_vars | combine( exp_base ) }}"
    ec2_instances_num: "{{ host_values.n }}"
    ec2_instances_max_num: "{{ host_values.n_max }}"
