---

instance_type: {{ cookiecutter.host_ec2_instance_type  }}
ec2_volume_size: {{ cookiecutter.host_ec2_volume_size  }}

ec2_image_id:  {{ cookiecutter.host_ec2_ami }}
ec2_volume_snapshot: {{ cookiecutter.host_ec2_volume_snapshot }}

slurm_job_minutes: {{ cookiecutter.slurm_job_minutes  }} # individual job time
slurm_cpu_cores: {{ cookiecutter.slurm_cpu_cores }}
slurm_cpu_mem_per_core_mb: {{ cookiecutter.slurm_cpu_mem_per_core_mb }}
slurm_gpu_number: {{ cookiecutter.slurm_gpu_number }}
slurm_gpu_min_mem_per_gpu_mb: {{ cookiecutter.slurm_gpu_min_mem_per_gpu_mb }}
slurm_gpu_model: ~ # if set to a specific GPU, then the slurm_gpu_min_mem_per_gpu_mb is ignored
slurm_env: {{ cookiecutter.slurm_env }}

{% raw %}
slurm_scratch_dir: "/cluster/scratch/{{ euler_user }}"
{% endraw %}

docker_image_id: "doe-ubuntu20"
docker_image_tag: "latest"
