---

- name: Read the experiment configuration
  include_vars:
    file: experiments/designs/{{ suite }}.yml
    name: experiments

#
# Add default values
#
- name: Add default for check_status if not set
  set_fact:
    experiments: "{{ experiments | dict_default('*.host_types.*', 'check_status', True) }}"
