---

##################################################################################
# This playbook sets up an ansible master on AWS. This instance is able to       #
# run the experiment playbook and gather the results. It is intended to be used  #
# as a long-running instance where GitHub actions can send commands to, to       #
# trigger experiment runs.                                                       #
##################################################################################

##########################################################################
#   Setup Ansible master                                             #
##########################################################################
- name: Create ansible master
  hosts: localhost
  tasks:

    - name: Template dynamic inventory config file
      # we do this because we want to filter the inventory for ansible masters
      # (such that only ec2 instances with a corresponding tag are visible)
      template:
        src: resources/inventory/aws_ec2.yml.j2
        dest: inventory/aws_ec2.yml
        mode: 0755
      vars:
        prj_clear: True

    # Load variables from doe-suite/src
    - name: Load group variables
      include_role:
        name: load-group-vars
      vars:
        groups_to_load:
          - all

    # Load variables for the ansible_master host type
    - name: Manually load variables for ansible_master
      include_vars:
          file: group_vars/ansible_master/main.yml

    - name: Setup AWS VPC
      include_role:
        name: suite-aws-vpc-create

    - name: Create AWS EC2 instance for ansible master
      include_role:
        name: ansible-master-ec2

- name: Setup ansible master
  hosts: ansible_master

  vars_prompt:
    - name: aws_access_key_id
      prompt: Enter your AWS access key id
      private: no
      default: NONE

    - name: aws_secret_access_key
      prompt: Enter your AWS secret access key
      default: NONE

    - name: ansible_master_slack_app_token
      prompt: Enter slack bot app-level token
      default: NONE

    - name: ansible_master_slack_bot_token
      prompt: Enter slack bot user OAuth token
      default: NONE

  tasks:
    - name: Load group variables
      include_role:
        name: load-group-vars
      vars:
        groups_to_load:
          - all

    - name: Configure the EC2 instance for running the AWS Ansible Experiment Suite
      include_role:
        name: ansible-master-setup
