---

- debug:
    msg: "-> small only"
  tags: [print_action]

- name: Download install-poetry.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
    dest: /tmp/get-poetry.py

- name: Install requirements.txt
  shell: |
    source /etc/profile
    source ~/.bash_profile
    . /cluster/apps/local/env2lmod.sh
    module load {{ euler_env }}
    python /tmp/get-poetry.py
    source $HOME/.poetry/env
    poetry export -f requirements.txt --output requirements.txt
    pip install --user -r requirements.txt
  args:
    chdir: "{{ exp_code_dir }}"
    executable: /bin/bash