---

- assert:
    that:
    - remote_results_dir is defined
    - local_results_dir is defined
    - remote_hosts is defined # list of {"host": "<HOST>", "host_type": "<type of host (e.g., server)>", "idx": "<IDX>"}
    - remote_config_file is defined

- name: Create local folder (for results)
  file:
    path: "{{ local_results_dir }}/{{ d.host_type }}_{{ d.idx }}"
    state: directory
    mode: 0755
  loop: "{{ remote_hosts }}" 
  loop_control:
    loop_var: d

- name: Fetch Results (if experiment done)
  delegate_to: localhost
  local_action: command rsync -az "{{ d.host }}:{{ remote_results_dir }}/*" "{{ local_results_dir }}/{{ d.host_type }}_{{ d.idx }}"
  loop: "{{ remote_hosts }}" 
  loop_control:
    loop_var: d

- name: fetch config
  ansible.builtin.fetch:
    src: "{{  remote_config_file }}"
    dest: "{{ local_results_dir }}/"
    flat: yes
    validate_checksum: no
  delegate_to: "{{ d.host }}"
  loop: "{{ remote_hosts }}" 
  loop_control:
    loop_var: d
  