---
# NOTE: At the moment `bsub` (LSF) is not used for scheduling tasks
#       but we leave the scheduler if we want to add a cloud later that uses LSF

# WARNING: Since the introduction of exp_job_ids_completing, the role is untested

- assert:
    that:
      - exp_name is defined
      - exp_job_ids_queued is defined
      - exp_job_ids_queued | length > 0

#- name: Debug bjobs
#  bjobs_info:
#  register: bjobs_result
#- name: debug bjobs
#  debug:
#    msg: "{{ bjobs_result }}"


- name: Get bjobs
  bjobs_info:
  register: bjobs_result
  until: exp_job_ids_queued | bsub_jobs_finished(bjobs_result.tasks) | length
  retries: "{{ job_n_tries }}"
  delay: "{{ job_check_wait_time }}"


- name: Marking jobs ids as completing
  set_fact:
    exp_job_ids_completing: "{{ exp_job_ids_queued | bsub_jobs_finished(bjobs_result.tasks) }}"
