---
- assert:
    that:
      - exp_name is defined
      - exp_job_ids_queued is defined
      - exp_job_ids_queued | length > 0

- name: Get status of job
  # Note: if the number of tries are exceeded, the task raises an error which stops this role and is caught in the parent
  tsp_info:
  register: tsp_result
  until: exp_job_ids_queued | tsp_jobs_finished(tsp_result.tasks) | length
  retries: "{{ job_n_tries }}"
  delay: "{{ job_check_wait_time }}"
  delegate_to: "{{ host }}"
  loop: "{{ groups[exp_name] | intersect(groups['check_status_yes']) }}" # only check status of jobs for host_types with 'check_status' == true
  loop_control:
    loop_var: host


- name: Marking jobs ids as completing
  set_fact:
    exp_job_ids_completing: "{{ exp_job_ids_queued | tsp_jobs_finished(tsp_result.results[-1].tasks) }}"
