---

# This role configures the dynamic inventory config file

- assert:
    that:
    - exp_base is defined
    - prj_clear is defined
    - does_inventory_source is defined

- name: Template dynamic inventory config file
  # we do this because we want to have the project id as an inventory filter (such that only ec2 instances with a corresponding tag are visible)
  template:
    src: resources/inventory/aws_ec2.yml.j2
    dest: "{{ does_inventory_source }}/aws_ec2.yml"
    mode: 0755
  vars:
    prj_clear: prj_clear # controls whether to also filter for the suite or not (for a clear we want to include all instances of the project independent of the suite)
    is_ansible_controller: False