---

##################################################################################
# This playbook sets up an ansible controller on AWS. This instance is able to   #
# run the experiment playbook and gather the results. It is intended to be used  #
# as a long-running instance where GitHub actions can send commands to, to       #
# trigger experiment runs.                                                       #
##################################################################################

##########################################################################
#   Setup Ansible Controller                                             #
##########################################################################
- name: Create ansible controller
  hosts: localhost
  tasks:

    - name: Template dynamic inventory config file
      # we do this because we want to have the project id as an inventory filter (such that only ec2 instances with a corresponding tag are visible)
      template:
        src: resources/inventory/aws_ec2.yml.j2
        dest: inventory/aws_ec2.yml
        mode: 0755
      vars:
        prj_clear: True
        is_ansible_controller: True

    # Load variables
    - name: Load group variables
      include_role:
        name: load-group-vars
      vars:
        groups_to_load:
          - all

    - name: Manually load variables for ansible_controller
      include_vars:
        dir: "{{ external_group_vars_dir }}/ansible_controller"
        ignore_unknown_extensions: True

    - name: Setup Cloud Network
      include_role:
        name: suite-cloud-network-create
        tasks_from: aws

    - name: Create AWS EC2 instance for ansible controller
      include_role:
        name: ansible-controller-ec2

- name: Setup ansible controller
  hosts: ansible_controller

  tasks:
    - name: Load group variables
      include_role:
        name: load-group-vars
      vars:
        groups_to_load:
          - all
          - ansible_controller

    - name: Configure the EC2 instance for running the AWS Ansible Experiment Suite
      include_role:
        name: ansible-controller-setup
