---

- name: Cleanup and Utility
  hosts: localhost

  tasks:
  - include_vars:
      dir: "{{ external_group_vars_dir }}/all"
      ignore_unknown_extensions: True

  - name: create directory for suite design  (if it does not exist)
    file:
      path: inventory
      state: directory
      mode:  0755

  - name: Template dynamic inventory config file
    template:
      src: resources/inventory/aws_ec2.yml.j2
      dest: inventory/aws_ec2.yml
      mode: 0755
    vars:
      prj_clear: True
      is_ansible_controller: False

  - name: Clear cloud instances
    include_role:
      name: suite-cloud-instances-delete
      tasks_from: "{{ 'suite-cloud-instances-delete' | multiplex_tasks(cloud) }}"

  - name: Clear cloud network
    include_role:
      name: suite-cloud-network-delete
      tasks_from: "{{ 'suite-cloud-network-delete' | multiplex_tasks(cloud) }}"
    when: exp_base.skip_network_delete is undefined or  exp_base.skip_network_delete == false
