---

- name: Cleanup and Utility
  hosts: localhost

  tasks:
  - include_vars:
      dir: "{{ external_group_vars_dir }}/all"
      ignore_unknown_extensions: True

  - set_fact:
      inventory_dir: "inventory/{{ prj_id }}"

  - name: create directory for suite design  (if it does not exist)
    file:
      path: "{{ inventory_dir }}"
      state: directory
      mode: 0755

  - name: Throw error when trying to clear other clouds
    fail:
      msg: "Cannot clear cloud '{{ cloud }}' as it is not a supported operation."
    when: cloud not in ['aws', 'docker']

  - name: Setup inventory
    include_role:
      name: suite-cloud-inventory-setup
      tasks_from: "{{ 'suite-cloud-inventory-setup' | multiplex_tasks(cloud) }}"
    vars:
      prj_clear: True
      does_inventory_source: "{{ inventory_dir }}"

  - name: Clear cloud instances
    include_role:
      name: suite-cloud-instances-delete
      tasks_from: "{{ 'suite-cloud-instances-delete' | multiplex_tasks(cloud) }}"

  - name: Clear cloud network
    include_role:
      name: suite-cloud-network-delete
      tasks_from: "{{ 'suite-cloud-network-delete' | multiplex_tasks(cloud) }}"
    when: exp_base.skip_network_delete is undefined or  exp_base.skip_network_delete == false

  - name: delete inventory directory
    file:
      path: "{{ inventory_dir }}"
      state: absent
