---

- name: Cleanup and Utility
  hosts: localhost

  tasks:
  - include_vars:
      dir: "{{ external_group_vars_dir }}/all"
      ignore_unknown_extensions: True


  - name: Template dynamic inventory config file
    template:
      src: resources/inventory/aws_ec2.yml.j2
      dest: inventory/aws_ec2.yml
      mode: 0755
    vars:
      prj_clear: True
      is_ansible_controller: False

  - name: Clear EC2 instances
    include_role:
      name: suite-cloud-ec2-delete
      tasks_from: "{{ 'suite-cloud-ec2-delete' | multiplex_tasks(cloud) }}"

  - name: Clear VPC
    include_role:
      name: suite-aws-vpc-delete
      tasks_from: "{{ 'suite-cloud-vpc-delete' | multiplex_tasks(cloud) }}"
    when: exp_base.skip_vpc_delete is undefined or  exp_base.skip_vpc_delete == false
