---

- name: Cleanup and Utility
  hosts: localhost

  tasks:
  - include_vars:
      dir: "{{ external_group_vars_dir }}/all"
      ignore_unknown_extensions: True

  - name: create directory for suite design  (if it does not exist)
    file:
      path: inventory
      state: directory
      mode: 0755

  # We could make this a separate role but that would be overkill, for now we can just multiplex on cloud here
  - name: Template dynamic inventory config file (AWS)
    template:
      src: resources/inventory/aws_ec2.yml.j2
      dest: inventory/aws_ec2.yml
      mode: 0755
    vars:
      prj_clear: True
      is_ansible_controller: False
    when: cloud == 'aws'

  - name: Template dynamic inventory config file (docker)
    template:
      src: resources/inventory/docker.yml.j2
      dest: inventory/docker.yml
      mode: 0755
    vars:
      prj_clear: True
      is_ansible_controller: False
    when: cloud == 'docker'

  - name: Throw error when trying to clear other clouds
    fail:
      msg: "Cannot clear cloud '{{ cloud }}' as it is not a supported operation."
    when: cloud not in ['aws', 'docker']

  - name: Clear cloud instances
    include_role:
      name: suite-cloud-instances-delete
      tasks_from: "{{ 'suite-cloud-instances-delete' | multiplex_tasks(cloud) }}"

  - name: Clear cloud network
    include_role:
      name: suite-cloud-network-delete
      tasks_from: "{{ 'suite-cloud-network-delete' | multiplex_tasks(cloud) }}"
    when: exp_base.skip_network_delete is undefined or  exp_base.skip_network_delete == false

