---

- name: Cleanup and Utility
  hosts: localhost

  tasks:
  - include_vars: "{{ external_group_vars_dir }}/all/main.yml"

  - name: Template dynamic inventory config file
    template:
      src: resources/inventory/aws_ec2.yml.j2
      dest: inventory/aws_ec2.yml
      mode: 0755
    vars:
      prj_clear: True
      is_ansible_controller: False

  - name: Clear EC2 instances
    include_role:
      name: suite-aws-ec2-delete

  - name: Clear VPC
    include_role:
      name: suite-aws-vpc-delete
    when: exp_base.skip_vpc_delete is undefined or  exp_base.skip_vpc_delete == false
