---

- include_tasks: prerequisites.yml
- include_tasks: ssh_setup.yml
# - include_tasks: fetch_does_repo.yml # TODO: reactivate when user was added to does repo!
- include_tasks: install_boto3.yml
- include_tasks: install_awscli.yml
- include_tasks: prepare_ansible.yml
- include_tasks: store_aws_creds.yml
