
- name: Install slackclient
  ansible.builtin.pip:
    name:
      - slack-sdk
      - slack-bolt
    executable: pip3
  become: yes
  become_method: sudo

- name: "Set environment variable {{ env_ctx.name }} permantently in /etc/environment"
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ env_ctx.name }}="
    line: "{{ env_ctx.name }}={{ env_ctx.value }}"
  when: env_ctx.value != 'NONE'
  loop:
    - { name: 'SLACK_APP_TOKEN', value: "{{ ansible_master_slack_app_token }}" }
    - { name: 'SLACK_BOT_TOKEN', value: "{{ ansible_master_slack_bot_token }}" }
    - { name: 'SSH_AUTH_SOCK', value: "{{ ansible_master_home }}/.ssh/ssh-agent.socket" }
    - { name: 'AWS_REGION_NAME', value: "{{ exp_base.aws_region }}" }
  loop_control:
    loop_var: env_ctx
  become: yes
  become_method: sudo

- name: Install systemd service for ssh-agent
  ansible.builtin.template:
    src: resources/systemd/system/ssh-agent.service.j2
    dest: /etc/systemd/system/ssh-agent.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  become_method: sudo

- name: Enable and start new ssh-agent service
  ansible.builtin.systemd:
    name: ssh-agent
    enabled: yes
    state: started
  become: yes
  become_method: sudo

- name: Install systemd service for slack bot
  ansible.builtin.template:
    src: resources/systemd/system/slack-bot.service.j2
    dest: /etc/systemd/system/slack-bot.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  become_method: sudo

- name: Reload systemd-daemon, enable, and (re)start slack bot service
  ansible.builtin.systemd:
    name: slack-bot
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes
  become_method: sudo
