
- name: Install slackclient
  ansible.builtin.pip:
    name:
      - slack-sdk
      - slack-bolt
    executable: pip3
  become: yes
  become_method: sudo

- name: "Set environment variable {{ env_ctx.name }} permantently in /etc/environment"
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ env_ctx.name }}="
    line: "{{ env_ctx.name }}={{ env_ctx.value }}"
  when: {{ env_ctx.name }} != 'NONE'
  loop:
    - {name: 'SLACK_APP_TOKEN', value: "{{ ansible_master_slack_app_token }}" }
    - {name: 'SLACK_BOT_TOKEN', value: "{{ ansible_master_slack_bot_token }}" }
  loop_control:
    loop_var: env_ctx
