name: Docs
on:
  push:
    branches:
      - "local"  # only deploy on main
  pull_request:
    branches:
      - "main"
#  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write


# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  DOES_PROJECT_DIR: ${{ github.workspace }}/demo_project
  DOES_PROJECT_ID_SUFFIX: "gh_action"
  DOES_DOCKER_SSH_PUBLIC_KEY: "~/.ssh/id_rsa.pub"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # checkout repo and setup python + poetry
      #----------------------------------------------
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
           python-version: '3.9'
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # generate keypair
      #----------------------------------------------
      - name: Generate SSH keypair
        run: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

      - name: Write to SSH config for localhost
        run: echo -e "Host 127.0.0.1 0.0.0.0\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tIdentityFile ~/.ssh/id_rsa\n\tUser ubuntu" > ~/.ssh/config
      - name: Set permissions for SSH config
        run: chmod 600 ~/.ssh/config

      - name: Make test
        working-directory: .
        run: make test-example01-minimal cloud=docker
