name: Docs
on:
#  push:
#    branches:
#      - "main"  # only deploy on main
  pull_request:
    branches:
      - "main"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "test"
  cancel-in-progress: true

env:
  DOES_PROJECT_DIR: ${{ github.workspace }}/demo_project
  DOES_PROJECT_ID_SUFFIX: "gh_action"
  DOES_DOCKER_SSH_PUBLIC_KEY: "~/.ssh/id_rsa.pub"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # checkout repo and setup python + poetry
      #----------------------------------------------
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
           python-version: '3.9'
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #-----------------------------------------------------------
      # generate keypair that we use to access the docker instance
      #-----------------------------------------------------------
      - name: Generate SSH keypair
        run: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
#
      - name: Write to SSH config for localhost
        run: echo -e "Host 127.0.0.1 0.0.0.0\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tUser ubuntu" > ~/.ssh/config
      - name: Set permissions for SSH config
        run: chmod 600 ~/.ssh/config

      - name: Test test-example01-minimal
        run: make test-example01-minimal cloud=docker

      - name: Test test-example02-single
        run: make test-example02-single cloud=docker

      - name: Test test-example03-format
        run: make test-example03-format cloud=docker

      - name: Test test-example04-multi
        run: make test-example04-multi cloud=docker

      - name: Test test-example05-complex
        run: make test-example05-complex cloud=docker

      - name: Test test-example06-vars
        run: make test-example06-vars cloud=docker

      - name: Test test-example07-etl
        run: make test-example07-etl cloud=docker

      - name: Test test-example08-superetl
        run: make test-example08-superetl cloud=docker
