name: Docs
on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write


# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  DOES_PROJECT_DIR: ${{ github.workspace }}/demo_project


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # checkout repo and setup python + poetry
      #----------------------------------------------
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
           python-version: '3.9'
      - uses: snok/install-poetry@v1
        with:
          version: 2.0.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # install dependencies
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
        working-directory: ./doespy
      - name: Install project
        run: poetry install --no-interaction
        working-directory: ./doespy
      #----------------------------------------------
      # run sphinx build
      #----------------------------------------------
      - name: Run Sphinx Build
        run: |
          source ./doespy/.venv/bin/activate
          sphinx-build docs/source _build